### ISSUE TITLE
gf run main.go

### ISSUE THREAD

**Issue by gamegg** [gogf/gf-cli#91]
最近几个版本的gf命令 运行后，第一次必然 报这个错，再次执行 就可以了，很奇怪(我的go version 是1.15.4 - 1.15.10 是我最近使用的)，这个bug 不影响使用

2021-03-21 13:15:00.037 build: main.go
2021-03-21 13:15:00.045 go build -o bin\main.exe  main.go
2021-03-21 13:15:10.955 bin\main.exe
2021-03-21 13:15:10.956 build running error: fork/exec bin\main.exe : The process cannot access the file because it is being used by another process.
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x367cad]

goroutine 132 [running]:
github.com/gogf/gf/os/gtimer.(*wheel).proceed.func1.1.1(0xc000672060)
        /Users/john/Workspace/Go/GOPATH/pkg/mod/github.com/gogf/gf@v1.15.4-0.20210301095002-bd13de2b39d7/os/gtimer/gtimer_loop.go:70 +0xb0
panic(0xa02d80, 0x119bc00)
        /usr/local/go/src/runtime/panic.go:969 +0x1c7
os.(*Process).signal(0x0, 0xc67e00, 0x10cf5c8, 0xc000672360, 0xc0003c6ce0)
        /usr/local/go/src/os/exec_windows.go:59 +0x2d
os.(*Process).Signal(...)
        /usr/local/go/src/os/exec.go:131
os.(*Process).kill(...)
        /usr/local/go/src/os/exec_posix.go:66
os.(*Process).Kill(...)
        /usr/local/go/src/os/exec.go:116
github.com/gogf/gf/os/gproc.(*Process).Kill(0xc0004aa160, 0x21, 0x0)
        /Users/john/Workspace/Go/GOPATH/pkg/mod/github.com/gogf/gf@v1.15.4-0.20210301095002-bd13de2b39d7/os/gproc/gproc_process.go:115 +0x56
github.com/gogf/gf-cli/commands/run.(*App).Run(0xc000348700)
        /Users/john/Workspace/Go/GOPATH/src/github.com/gogf/gf-cli/commands/run/run.go:192 +0x6b3
github.com/gogf/gf-cli/commands/run.Run.func2.1()
        /Users/john/Workspace/Go/GOPATH/src/github.com/gogf/gf-cli/commands/run/run.go:144 +0x105
github.com/gogf/gf/os/gtimer.(*wheel).proceed.func1.1(0xc000672060)
        /Users/john/Workspace/Go/GOPATH/pkg/mod/github.com/gogf/gf@v1.15.4-0.20210301095002-bd13de2b39d7/os/gtimer/gtimer_loop.go:79 +0x55
created by github.com/gogf/gf/os/gtimer.(*wheel).proceed.func1
        /Users/john/Workspace/Go/GOPATH/pkg/mod/github.com/gogf/gf@v1.15.4-0.20210301095002-bd13de2b39d7/os/gtimer/gtimer_loop.go:66 +0x137

**Comment by gqcn** [comment]
这个需要进一步分析，优先级不高，先保留。
